### ISSUE TITLE
git install not working

### ISSUE THREAD

**Issue by RobertArbon** [markovmodel/PyEMMA#1195]
I did: 

```
Research ➤ git clone git@github.com:RobertArbon/PyEMMA.git
cd PyEMMA
PyEMMA ➤ python setup.py develop                                                                                                                               git:7ed62207
setup.py:274: UserWarning: using git, require cython
  warnings.warn('using git, require cython')
Submodule 'pybind11' (https://github.com/pybind/pybind11) registered for path 'pybind11'
Cloning into '/Users/robert_arbon/Google Drive/Research/PyEMMA/pybind11'...
Submodule path 'pybind11': checked out '1df91d36cfa997c8987889234304ea5e37cc3e68'
```
and then I get the following error: 
```
pybind11/include/pybind11/common.h:126:10: fatal error: 'forward_list' file not found
#include <forward_list>
         ^~~~~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1
```

This is strange because I did a git install just a few days ago. 

I don't know enough about submodules or pybind11 to comment much further, except to say that:

- The problem seems to be that the submodule is updating to an old version of `pybind11`  - version 2.1 and that requires the header file `forward_list` which can't be found. 

- I notice that the latest version of pybind11 is 2.2 and that has deprecated the `common.h` file. 

I've tried specifying the stable branch in `.gitmodules` file i.e. 
```
[submodule "pybind11"]
	path = pybind11
	url = https://github.com/pybind/pybind11
        branch = stable
```
but the command line call in `setup.py` seems to override that. 

I've also checked out commit `7ed622076b004f8a114f7f5b42fe9585a566e8e1` on `devel` from 3 days ago but the problem persists.  

I've tried manually updating the PyEMMA/pybind11/ submodule to the latest version before running `setup.py` but the `        cmd = "git submodule update --init {mod}"` seems to override that and install the old version (2.1). 

I'm on OSX Sierra.

**Comment by marscher** [comment]
Thanks the report. Ain't clang cxx11 compatible? Any how I pushed a branch to use the latest release of pybind. What is the exact clang invocation here?

**Comment by marscher** [comment]
I guess just updating the version will not solve your problem, because the compiler flags should have told clang to use at least cxx11 standard to compile the code. Probably apple broke the gcc command line options compatibility again...

**Comment by RobertArbon** [comment]
yes, there was an update on 29th November to command line tools which might have been responsible but I thought I did an install on the 30th.  Once I figure it out I'll post an update.

**Comment by clonker** [comment]
This sounds to me like it tries to link against the wrong standard library (per default clang++ on osx links against a std lib that has no c++11 capabilities). Can you try and add a `-stdlib=libc++` to `extra_compile_args` of the clustering module and the covar module in `setup.py`? That one should support c++11.

**Comment by marscher** [comment]
On 12/04/2017 02:52 PM, Moritz Hoffmann wrote:
> This sounds to me like it tries to link against the wrong standard
> library (per default clang++ on osx links against a std lib that has no
> c++11 capabilities). Can you try and add a |-stdlib=libc++| to
> |extra_compile_args| of the clustering module and the covar module in
> |setup.py|? That one should support c++11.
That should solve it. Thank you for the hint!

**Comment by marscher** [comment]
@RobertArbon can you confirm that this works with the following command? 

pip install git+https://github.com/marscher/pyemma@fix_compilation_darwin -v

**Comment by RobertArbon** [comment]
If failed with the following: 

```
    In file included from pyemma/coordinates/clustering/include/bits/../metric_base.h:94:
    pyemma/coordinates/clustering/include/bits/metric_base_bits.h:12:10: fatal error: 'omp.h' file not found
    #include <omp.h>
             ^~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit status 1
```
I'm updating setuptools and trying again. 

Update: no - still not working.  Same error.

**Comment by marscher** [comment]
that is funny, because we are checking if the compiler has support for
OMP and include guard the statement. Can you please upload a
comprehensive logfile of the setup process?

**Comment by marscher** [comment]
my statement is only have true. The include guard does not help in this
case, because before this one omp.h is already included.

Kind of funny that Apple does not even include OpenMP in the default
install.

**Comment by RobertArbon** [comment]
I'm not sure what has happened because as I said it was working a few days ago.  I'm running the install again and will include logs etc.

**Comment by marscher** [comment]
Actually you've discovered another bug (including omp.h even if it is
not available). It could also be, that clang needs another kind of check
for OpenMP.

**Comment by RobertArbon** [comment]
[conda_list.txt](https://github.com/markovmodel/PyEMMA/files/1527921/conda_list.txt)
[pyemma_install_log.txt](https://github.com/markovmodel/PyEMMA/files/1527922/pyemma_install_log.txt)

```
(ml4dyn) Research ➤ clang --version
Apple LLVM version 9.0.0 (clang-900.0.37)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by marscher** [comment]
Thanks! Does it happen with latest commit too?

**Comment by RobertArbon** [comment]
from latest markovmodel/pyemma

[pyemma_install_log_devel.txt](https://github.com/markovmodel/PyEMMA/files/1528036/pyemma_install_log_devel.txt)

from latest at marscher/pyemma
[pyemma_install_log_marscher_devel.txt](https://github.com/markovmodel/PyEMMA/files/1528037/pyemma_install_log_marscher_devel.txt)

**Comment by marscher** [comment]
sorry I wanted you to retest the pip command I've posted here, because
this points to the proposed fixes. I also do not need the output of it.
Thank you very much!

**Comment by RobertArbon** [comment]
Boom!  
```
Successfully installed pyEMMA-2.4+483.g27f3730a
```
Excellent thank you (Y)

**Comment by marscher** [comment]
thank you for testing!

**Comment by marscher** [comment]
however it fails now if the compiler is gcc (which is also used by some
people on OSX).
