### ISSUE TITLE
emma version not set when installing from setup.py

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#148]
When installing from setup.py, the emma version seems not to be set:

>>> import pyemma
>>> pyemma.__version__
'unknown'

**Comment by marscher** [comment]
Am 26.03.2015 um 21:43 schrieb Frank Noe:
> When installing from setup.py, the emma version seems not to be set:
>
>             import pyemma
>             pyemma.*version*
>             'unknown'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/markovmodel/PyEMMA/issues/148>.
>
This is the wrong usage of version

!google python version attribute

https://www.python.org/dev/peps/pep-0396/#id24

You should try the __version__ attribute.



numpy does it like numpy.VERSION and FULLVERSION

If you think this more convenient, we can change it easily. You might 
then consider to change the title of this issue, since the attribute is 
working.

**Comment by franknoe** [comment]
I swear this was a copy error (no idea why). Actually I did use:

 >>> pyemma.__version__
'unknown'

But for a reason I can't understand it works now.


I just installed again and got the error "no module regspace". Then I 
reinstalled with the
     python setup.py develop
and then it worked ... weird. Why does that happen?



Am 26/03/15 um 21:47 schrieb Martin K. Scherer:
> Am 26.03.2015 um 21:43 schrieb Frank Noe:
> > When installing from setup.py, the emma version seems not to be set:
> >
> > import pyemma
> > pyemma.*version*
> > 'unknown'
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/markovmodel/PyEMMA/issues/148>.
> >
> This is the wrong usage of version
>
> !google python version attribute
>
> https://www.python.org/dev/peps/pep-0396/#id24
>
> You should try the __version__ attribute.
>
>
>
> numpy does it like numpy.VERSION and FULLVERSION
>
> If you think this more convenient, we can change it easily. You might
> then consider to change the title of this issue, since the attribute is
> working.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86708708>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
I tried again. So when I import pyemma from a shell in the install 
directory it works:

 >>> import pyemma
 >>> pyemma.__version__
'1.1.2-51-g29f48b8'

When I do exactly the same in another directory it does not:

 >>> import pyemma
 >>> pyemma.__version__
'1.1.2'

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Sorry, but

'unknown' seems like a valid value to me (e.g intended). Maybe git did 
not know about the version tags during the invocation of setup.py?

This might then lead to such super unknown issues.

git fetch --tags seems to be necessary on older git versions (since I'm 
using recent stables on linux I've might not runned into this).

**Comment by marscher** [comment]
Makes perfect sense to me. The version number surely depends on where 
pyemma is being imported from:

* First output (you're importing from you git clone)
* Second is the installed version which lies on your global PYTHONPATH.

**Comment by franknoe** [comment]
Sorry, that does not help me. Shouldn't executing
      python setup.py install
Install Emma, such that I can import this version from wherever???

Am 26/03/15 um 21:59 schrieb Martin K. Scherer:
> Makes perfect sense to me. The version number surely depends on where
> pyemma is being imported from:
>
> * First output (you're importing from you git clone)
> * Second is the installed version which lies on your global PYTHONPATH.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86713334>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Am 26.03.2015 um 22:02 schrieb Frank Noe:
> Sorry, that does not help me. Shouldn't executing
> python setup.py install
> Install Emma, such that I can import this version from wherever???
sure it does.

So you've installed after a recent git fetch --tags?

Is the __version__ attribute now something with a git hash not matter 
where you import from?

**Comment by franknoe** [comment]
Am 26/03/15 um 22:04 schrieb Martin K. Scherer:
> Am 26.03.2015 um 22:02 schrieb Frank Noe:
> > Sorry, that does not help me. Shouldn't executing
> > python setup.py install
> > Install Emma, such that I can import this version from wherever???
> sure it does.
>
> So you've installed after a recent git fetch --tags?
yes.
>
> Is the __version__ attribute now something with a git hash not matter
> where you import from?
I don't know what that means.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86717035>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Ok. Quick reminder on imports in Python:

if you've got a module/package "foo" in your current location of your 
shell (or working dir of a process (ipython notebook etc.), and you

     import foo

the first lookup match will be in that dir.

     $ ls -R $(pwd)
     foo
     foo/__init.py__



If its not found there, the "sys.path" list will be taken into account, 
till its found or ImportError is raised.

If you know import pyemma from

~/work/git/pyemma/

The version will be the development version of the current branch your 
working on.

If you've installed pyemma globally (eg. with conda) and its being 
imported from there (pyemma dir is not the location of your shell), the 
version has to be something converged like "1.1.2" (hopefully we release 
1.1.3 soon).

But I'm really sure, that this behavior exactly what we want, since you 
need to be able to distinguish between versions during runtime. This 
pattern is being found in NumPy/SciPy/whatever big project.

**Comment by franknoe** [comment]
OK, fine. But I would like that my installation command
     python setup.py install
Installs pyemma in such a way that this version is available everywhere 
in the system when I import pyemma.

For example in ipython it is, although I do definitely not run ipython 
from the installation directory. In ipython the __version__ command 
gives 1.1.2. From the command line (i.e. from other directories) it 
gives unknown.

Am 26/03/15 um 22:17 schrieb Martin K. Scherer:
> Ok. Quick reminder on imports in Python:
>
> if you've got a module/package "foo" in your current location of your
> shell (or working dir of a process (ipython notebook etc.), and you
>
> import foo
>
> the first lookup match will be in that dir.
>
> $ ls -R $(pwd)
> foo
> foo/__init.py__
>
>
>
> If its not found there, the "sys.path" list will be taken into account,
> till its found or ImportError is raised.
>
> If you know import pyemma from
>
> ~/work/git/pyemma/
>
> The version will be the development version of the current branch your
> working on.
>
> If you've installed pyemma globally (eg. with conda) and its being
> imported from there (pyemma dir is not the location of your shell), the
> version has to be something converged like "1.1.2" (hopefully we release
> 1.1.3 soon).
>
> But I'm really sure, that this behavior exactly what we want, since you
> need to be able to distinguish between versions during runtime. This
> pattern is being found in NumPy/SciPy/whatever big project.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86721681>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by franknoe** [comment]
Or let me ask differently: I have downloaded pyemma from git. Now I want 
to install this version such that anywhere on my system it is used when I do
     import pyemma
And not some other version that was installed previously (in any way).

How do I do that?

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
If setup.py install have not done it, I fear there is something borked 
in your system (since this setup is working for all my testing systems).

Need some debug info:

      python setup.py version

(should print something like 1.1.2-hash-(post-commit-nr)

and

      import pyemma
      print pyemma.__path__

and

     import sys
     for p in sys.path:
         print p

**Comment by franknoe** [comment]
OK:

Am 26/03/15 um 23:42 schrieb Martin K. Scherer:
> python setup.py version
>
> (should print something like 1.1.2-hash-(post-commit-nr)
panda:pyemma noe$ python setup.py version
setup.py:249: UserWarning: using git, require cython
   warnings.warn('using git, require cython')
/Users/noe/anaconda/lib/python2.7/site-packages/setuptools-12.2-py2.7.egg/setuptools/dist.py:291: 
UserWarning: The version specified ('1.1.2-51-g29f48b8') is an invalid 
version, this may not work as expected with newer versions of 
setuptools, pip, and PyPI. Please see PEP 440 for more details.
running version
got version from VCS {'version': '1.1.2-51-g29f48b8', 'full': 
'29f48b8443c4e5c8391bd50fd4d1a8acd75bd739'}
Version is currently: 1.1.2-51-g29f48b8

> import pyemma
> print pyemma.__path__
that depends. Within the git copy directory it is

 >>> import pyemma
 >>> print pyemma.__path__
['pyemma']

elsewhere it is:

 >>> import pyemma
 >>> pyemma.__path__
['/Users/noe/anaconda/lib/python2.7/site-packages/pyemma']

so actually different as you suggested.

In ipython it is also
['/Users/noe/anaconda/lib/python2.7/site-packages/pyemma']

But for some reason in ipython the __version__ is set correctly.
>
> and
>
> import sys
> for p in sys.path:
> print p
Again, depends:
in the pyemma git directory
/Users/noe/data/papers/ChoderaEtAl_BHMM/bhmm
/Users/noe/anaconda/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/pystallone-1.0.0b7-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/oasis-0.1.0-py2.7.egg
/Users/noe/anaconda/lib/python27.zip
/Users/noe/anaconda/lib/python2.7
/Users/noe/anaconda/lib/python2.7/plat-darwin
/Users/noe/anaconda/lib/python2.7/plat-mac
/Users/noe/anaconda/lib/python2.7/plat-mac/lib-scriptpackages
/Users/noe/anaconda/lib/python2.7/lib-tk
/Users/noe/anaconda/lib/python2.7/lib-old
/Users/noe/anaconda/lib/python2.7/lib-dynload
/Users/noe/.local/lib/python2.7/site-packages
/Users/noe/anaconda/lib/python2.7/site-packages/runipy-0.1.1-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/scripttest-1.3-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/setuptools-12.2-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages
/Users/noe/anaconda/lib/python2.7/site-packages/PIL
/Users/noe/anaconda/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/pyEMMA-1.1.1-py2.7-macosx-10.5-x86_64.egg
/Users/noe/data/software_projects/pyemma

elsewhere:

/Users/noe/data/papers/ChoderaEtAl_BHMM/bhmm
/Users/noe/anaconda/lib/python2.7/site-packages/docopt-0.6.2-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/pystallone-1.0.0b7-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/oasis-0.1.0-py2.7.egg
/Users/noe/anaconda/lib/python27.zip
/Users/noe/anaconda/lib/python2.7
/Users/noe/anaconda/lib/python2.7/plat-darwin
/Users/noe/anaconda/lib/python2.7/plat-mac
/Users/noe/anaconda/lib/python2.7/plat-mac/lib-scriptpackages
/Users/noe/anaconda/lib/python2.7/lib-tk
/Users/noe/anaconda/lib/python2.7/lib-old
/Users/noe/anaconda/lib/python2.7/lib-dynload
/Users/noe/.local/lib/python2.7/site-packages
/Users/noe/anaconda/lib/python2.7/site-packages/runipy-0.1.1-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/scripttest-1.3-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/setuptools-12.2-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages
/Users/noe/anaconda/lib/python2.7/site-packages/PIL
/Users/noe/anaconda/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg
/Users/noe/anaconda/lib/python2.7/site-packages/pyEMMA-1.1.1-py2.7-macosx-10.5-x86_64.egg
/Users/noe/data/papers/ClementiNoe_SparseSampling
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86743405>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
So to clarify this:

If you import pyemma it contains the version you're using. If thats not 
the case, you've discovered a bug. But again, the output makes total sense:

/Users/noe/anaconda/lib/python2.7/site-packages/pyemma

contains the conda version which has version 1.1.2

If you've installed from git either via setup.py install or develop,
you get a git version when importing.

Please note that setup.py install creates a package and installs it to 
your global python path (think of a snapshot of current state, being 
installed), where develop will create a *permanent* link to your git folder.

The difference to install mode is, that you will get a new version after 
every commit.

Now what can be red from our output is the following:

> that depends. Within the git copy directory it is
>
>  >>> import pyemma
>  >>> print pyemma.__path__
> ['pyemma']
__version__ should be "1.1.2-51-g29f48b8"
>
> elsewhere it is:
>
>  >>> import pyemma
>  >>> pyemma.__path__
> ['/Users/noe/anaconda/lib/python2.7/site-packages/pyemma']
pyemma.__version__ should now be 1.1.2
>
> so actually different as you suggested.
?
>
> In ipython it is also
> ['/Users/noe/anaconda/lib/python2.7/site-packages/pyemma']
>
> But for some reason in ipython the __version__ is set correctly.
What is correct in your opinion?

**Comment by franknoe** [comment]
Now suddenly pyemma.__version__ outputs 1.1.2 in all shells, including 
these where it was 'unknown' before. I don't understand this ... is 
there some daemon which updates these things occasionally? Very confusing.

In any case, just to be sure I understand:

In my git directory I get
 >>> import pyemma
 >>> pyemma.__version__
'1.1.2-51-g29f48b8'
 >>> pyemma.__path__
['pyemma']

Elsewhere I (now) get
 >>> import pyemma
 >>> pyemma.__version__
'1.1.2'
 >>> pyemma.__path__
['/Users/noe/anaconda/lib/python2.7/site-packages/pyemma']

These are two different versions, correct? So how do I make sure that an 
import pyemma everywhere leads to using the same version?

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
I've updated the versioneer module to get pep440 compatible version strings for dirty (unreleased) commits. Your issue should be fixed now

**Comment by marscher** [comment]
fixed by 57606d3cd9823f3f693451cb16be63b95944fdb8

**Comment by franknoe** [comment]
Yes, congrats!

Searching for pyEMMA==1.1.2+55.g13c2350
Best match: pyEMMA 1.1.2+55.g13c2350
pyEMMA 1.1.2+55.g13c2350 is already the active version in easy-install.pth

BTW, StrictVersion still doesn't work, but LooseVersion does. I guess 
that is intended.

Am 27/03/15 um 15:53 schrieb Martin K. Scherer:
>
> I've updated the versioneer module to get pep440 compatible version 
> strings for dirty (unreleased) commits. Your issue should be fixed now
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86963230>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by marscher** [comment]
Yes!

StrictVersion :  Version numbering for anal retentives and software idealists.

LooseVersion :  Version numbering for anarchists and software realists.

**Comment by marscher** [comment]
This is a quote from http://svn.python.org/projects/python/branches/pep-0384/Lib/distutils/version.py :)

**Comment by franknoe** [comment]
Nice, I just learned a new word.

Am 27/03/15 um 16:05 schrieb Martin K. Scherer:
>
> Yes!
>
> StrictVersion : Version numbering for anal retentives and software 
> idealists.
>
> LooseVersion : Version numbering for anarchists and software realists.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/PyEMMA/issues/148#issuecomment-86966097>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
