### ISSUE TITLE
Implied Timescales with error estimation generates many progressbars

### ISSUE THREAD

**Issue by franknoe** [markovmodel/PyEMMA#501]
Implied timescales with error estimation shows a progress bar for each timescale. This is not desired. I think the problem is that progress bars are created rather low-level, but the decision of now progress bars are shown should be made on the highest level (at the API function). 

In this case, can the ImpliedTimescales estimator switch off the individual progress bars for the estimator it uses and instead just show one progress bar which steps by lag times computed?

What would be cooler (but probably more complicated) is that the high-level function (ImpliedTimescales) allocates a progress bar, and the called functiones (BayesianMSM) just fill a section of that bar given to it.

**Comment by marscher** [comment]
I can change this behavior. The underlying individual processes will
then be switched of by the ITS class.

Shall we add the progress argument to every estimation api function? I'd
like to add **kw to all api functions and just catch a variable
"show_progress" with True/False.

**Comment by franknoe** [comment]
Am 25/08/15 um 15:24 schrieb Martin K. Scherer:

> I can change this behavior. The underlying individual processes will
> then be switched of by the ITS class.
> Thanks, that would be good!
> 
> Shall we add the progress argument to every estimation api function? I'd
> like to add **kw to all api functions and just catch a variable
> "show_progress" with True/False.
> Would that mean we would need to change bhmm and re-release it as well, 
> right?

I am not familiar with how the progress bars are implemented at the 
moment and where they are actually shown. I could look into this, but 
probably this is not trivial and deserves a bit more discussion.

The lower-level function updates the progress bar by calling a callback 
function, correct? So could the higher-level function simply control the 
effect of that call and e.g. reserve a fraction of an existing progress 
bar to be updated by the lower-level call?

Alternatively, for ITS it would also be OK if we always show a single 
progress bar but overwrite that. Just the text then needs to say what is 
currently done, e.g. "Estimating MSM at lag=10", then the progress bar 
fills, then it resets and shows "Estimating MSM at lag=20", etc.

 From the user's point of view, a general way to deal with multi-level 
algorithms is to have these progress bars with local and global 
progress, but again I have no idea if that would be acceptably simply to 
implement and fit to our code structure:

```
 http://miktex.org/img/basic-miktex-filecopy-2-9.png?width=400
```

For now I'd say find a working solution for ITS (and probably also for 
the cktest), and we'll think of a generic solution later.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 25.08.2015 um 15:34 schrieb Frank Noe:

> Am 25/08/15 um 15:24 schrieb Martin K. Scherer:
> 
> > I can change this behavior. The underlying individual processes will
> > then be switched of by the ITS class.
> > Thanks, that would be good!
> > 
> > Shall we add the progress argument to every estimation api function? I'd
> > like to add **kw to all api functions and just catch a variable
> > "show_progress" with True/False.
> > Would that mean we would need to change bhmm and re-release it as well,
> > right?
> > No, that is not necessary.
> 
> I am not familiar with how the progress bars are implemented at the
> moment and where they are actually shown. I could look into this, but
> probably this is not trivial and deserves a bit more discussion.
> 
> The lower-level function updates the progress bar by calling a callback
> function, correct? So could the higher-level function simply control the
> effect of that call and e.g. reserve a fraction of an existing progress
> bar to be updated by the lower-level call?
> Only "external" algorithms like T-matrix sampling in msmtools and bhmm
> estimators update their progress by a call back function. If the
> underlying algorithm is under control of an estimator, the interface of
> ProgressReporter is directly used eg by _progress_update()
> 
> Alternatively, for ITS it would also be OK if we always show a single
> progress bar but overwrite that. Just the text then needs to say what is
> currently done, e.g. "Estimating MSM at lag=10", then the progress bar
> fills, then it resets and shows "Estimating MSM at lag=20", etc.
> This would be nice to have, but the logic of what is the global and
> local progress has to be implemented for every Reporter.
> 
> From the user's point of view, a general way to deal with multi-level
> algorithms is to have these progress bars with local and global
> progress, but again I have no idea if that would be acceptably simply to
> implement and fit to our code structure:
> It is possible but requires some work
> 
> http://miktex.org/img/basic-miktex-filecopy-2-9.png?width=400
> 
> For now I'd say find a working solution for ITS (and probably also for
> the cktest), and we'll think of a generic solution later.
> Sounds good to me.

**Comment by franknoe** [comment]
Probably related: msm.timescales_hmsm without "error" argument shows one 
progress bar with a single jump from 0 to 100%.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Am 25.08.2015 um 16:05 schrieb Frank Noe:

> Probably related: msm.timescales_hmsm without "error" argument shows one
> progress bar with a single jump from 0 to 100%.
> Maybe we should implement a trigger which waits for a certain amount of
> updates, calculate the ETA and only show the GUI, if ETA > threshold.

**Comment by franknoe** [comment]
Maybe, but I think this is a different issue. If the ITS algorithm shows 
the fraction of lags computed in its progress bar, I think this will be 
solved.

Am 25/08/15 um 16:07 schrieb Martin K. Scherer:

> Am 25.08.2015 um 16:05 schrieb Frank Noe:
> 
> > Probably related: msm.timescales_hmsm without "error" argument shows one
> > progress bar with a single jump from 0 to 100%.
> > Maybe we should implement a trigger which waits for a certain amount of
> > updates, calculate the ETA and only show the GUI, if ETA > threshold.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/501#issuecomment-134597351.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
done

**Comment by franknoe** [comment]
It still doesn't behave like desired, but I think now I understand 
what's going on. ImpliedTimescale does two things:
1. Estimate a model (MSM / BMSM / HMM / BHMM) at each lag time
2. Compute timescales/uncertainties for each of these

I think you have implemented a progress bar for ImpliedTimescales for 
step 2, but ImpliedTimescales does nothing for step 1 - right? In many 
cases Step 1 is the slow step, which explains why I observe that the 
process is waiting for a long time, and then shows a full progress bar 
instantly (which confusingly shows 'estimating' although it is really a 
'computing timescales').
On the other hand, when using a Bayesian MSM or Bayesian HMM estimator, 
one gets a timescale for each single lag time estimate in Step 1 
(because these estimators do implement a progress bar), and then 
afterwards ImpliedTimescales shows a (generally rapidly filling) 
progress bar for Step 2.

Is that all correct? In that case I think what ImpliedTimescales should 
do is to show two progess bars, one for Step 1 called 'estimating' and 
one for Step 2 called 'computing timescales'. In Step 1, the underlying 
Estimator (especially BayesianMSM and BayesianHMM) must be prevented to 
print its own progress bar to avoid the appearance of a separate 
progress bar for every lag time.

Am 25/08/15 um 22:28 schrieb Martin K. Scherer:

> Closed #501 https://github.com/markovmodel/PyEMMA/issues/501.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/markovmodel/PyEMMA/issues/501#event-392113192.

## 

---

Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de

## Mail:  Arnimallee 6, 14195 Berlin, Germany

**Comment by marscher** [comment]
Sorry for the inconvenience, the fix is still not yet merged on devel (it is on branch Py3)

**Comment by franknoe** [comment]
Automatic closing is not done for `msm.timescales_hmsm`

**Comment by marscher** [comment]
done with #515
