### ISSUE TITLE
Issue solving PCCA samples in release version 2.2

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/PyEMMA#840]
So we have run into some problems saving frames that would correspond to a series of PCCA states. 

To be precise, calling pyemma.coordinates.save_trajs() to save pcca sampled snapshots was not saving any files and lead to an error termination finishing with the following statement.

```
/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/_impl.pyc in set_numerator(self, numerator, calculate)
  148         # Validate
  149         if self._timing_data and numerator < self._timing_data[-1][1]:
--> 150             raise ValueError('numerator cannot decrement.')
  151 
  152         # Update data.

ValueError: numerator cannot decrement.

I traced back the error to a class called ProgressReporter() called in

~ /pyemma/coordinates/data/util/frames_from_file.py
```

Commenting out lines 126 127 132 and 133 of that file seemed to get rid off the error and now the files are saved correctly, though this is obviously quite a dirty solution. 
Here is the exact call in which the error occurs:

```
M = bayesian_markov_model(dtrajs,lagtime)
Import pyemma.coordinates as coor
inp=coor.source(trajfiles, topology)
[…]
pcca = M.pcca(8)
ppca_dist = M.metastable_distributions
pcca_samples = M.sample_by_distribution(pcca_dist,1000/500/100) #(same behaviour)
coor.save_trajs(inp,pcca_samples,outfiles=[8 str], inmemory =True/False )# (same behaviour)
```

**Comment by marscher** [comment]
Thanks for your report. Can you please show us the un-truncated 
stacktrace please?

**Comment by ppxasjsm** [comment]
It'll take a while to run. I'll get back to you.

**Comment by giopina** [comment]
I think I'm facing the very same problem
It seems to happen when I try to  use save_trajs to save a large (>200) number of frames.

**Comment by ppxasjsm** [comment]
The full error trace is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-ffed8461e3b7> in <module>()
----> 1 coor.save_trajs(inp, pcca_samples, outfiles=[clust1,clust2,clust3,clust4,clust5,clust6,clust7,clust8], inmemory=True)

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/api.pyc in save_trajs(traj_inp, indexes, prefix, fmt, outfiles, inmemory, stride, verbose)
   769     # This implementation is "one file - one pass" but might temporally create huge memory objects
   770     else:
--> 771         traj = save_traj(traj_inp, indexes, outfile=None, stride=stride, verbose=verbose)
   772         i_idx = 0
   773         for i_indexes, outfile in zip(indexes, outfiles):

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/api.pyc in save_traj(traj_inp, indexes, outfile, top, stride, chunksize, verbose)
   651                          % (len(trajfiles), indexes[0].max()))
   652 
--> 653     traj = frames_from_files(trajfiles, top, indexes, chunksize, stride, reader=reader)
   654 
   655     # Return to memory as an mdtraj trajectory object

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/coordinates/data/util/frames_from_file.py in frames_from_files(files, top, frames, chunksize, stride, verbose, copy_not_join, reader)
   131             collected_frames.append(x)
   132             reporter._progress_update(1)
--> 133     reporter._progress_force_finish()
   134 
   135     dest = _preallocate_empty_trajectory(top, len(frames))

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/reporter.pyc in _progress_force_finish(self, stage)
   202         if not isinstance(pg, _ProgressBar):
   203             return
--> 204         pg.numerator = pg.denominator
   205         pg._eta.eta_epoch = 0
   206         _show_progressbar(pg, description=self._prog_rep_descriptions[stage])

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/_impl.pyc in numerator(self, value)
   253         # If ETA is every iteration, don't do anything fancy.
   254         if self.eta_every <= 1:
--> 255             self._eta.numerator = value
   256             self._eta_string = self._generate_eta(self._eta.eta_seconds)
   257             return

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/_impl.pyc in numerator(self, value)
    77     def numerator(self, value):
    78         """Sets a new numerator (adds to timing data table). Must be greater than or equal to previous numerator."""
---> 79         self.set_numerator(value)
    80 
    81     @property

/home/soft/miniconda2/lib/python2.7/site-packages/pyEMMA-2.2-py2.7-linux-x86_64.egg/pyemma/_base/progress/bar/_impl.pyc in set_numerator(self, numerator, calculate)
   148         # Validate
   149         if self._timing_data and numerator < self._timing_data[-1][1]:
--> 150             raise ValueError('numerator cannot decrement.')
   151 
   152         # Update data.

ValueError: numerator cannot decrement.
```

**Comment by franknoe** [comment]
I think this is solved - at least the issue is closed. Have you tried updating?

**Comment by ppxasjsm** [comment]
Yeah sorry, my browser hadn't updated and then I already posted. All ok.

**Comment by giopina** [comment]
I am still getting apparently the same error.
I'm using the conda version of pyemma 2.2.1
